#!/bin/bash
# Assign user argument to a variable
path=$1
# Create app directory
mkdir $path
# Copy files to new directory
cp assets/app-* $path
mv $path/app-index.html $path/index.html
mv $path/app-script.js $path/script.js